services:
  app:
    build:
      context: ./docker/php
    container_name: bedrock_app
    volumes:
      - .:/var/www/html
      - ./web:/var/www/html/web
      - ./vendor:/var/www/html/vendor
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - bedrock_net

  nginx:
    image: nginx:latest
    container_name: bedrock_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html/web
      - ./vendor:/var/www/html/vendor
    depends_on:
      - app
    networks:
      - bedrock_net

  db:
    image: mysql:5.7
    container_name: bedrock_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bedrock_net

volumes:
  db_data:


networks:
  bedrock_net:
